### ISSUE TITLE
loading rockstar halos outside of gadget-hdf5 snapshot directory

### ISSUE THREAD

**Issue by bgriffen** [pynbody/pynbody#235]
I would like to load rockstar halos into my data set. 
```
h = s.halos()
```
Does not work as my directory structure is as follows (for one snapshot)
```
/gadget_sim/outputs/snapdir_255/
/gadget_sim/halos/halos_255/
```
Is it possible to specify the directory halos() reads from as they are not in the same directory as "outputs/".

Thanks.

**Comment by apontzen** [comment]
Hi Ben, Looking at @stinsong4100's implementation, it looks to me like you can pass in `filename='/path/to/rockstar.catalogue'` but I've never tried it to be sure...

**Comment by stinsong4100** [comment]
I'm afraid I never finished my rockstar implementation.  I got it basically working with tipsy and found that it was not including all the particles inside the virial radius in its halo definition when I ran rockstar-galaxies on a simulation that included gas and stars along with dark matter, so I gave up since fixing that problem seemed like it would take a long time.  However, any complete n-body module should include rockstar support, so any coding help you can provide would be greatly appreciated, especially extending the utilty to Gadget.

**Comment by apontzen** [comment]
It doesn't seem like anyone is working on the rockstar support at the moment so I am closing this issue. Hopefully someone will pick up full rockstar support later.
