### ISSUE TITLE
The pynbody.plot.sph.image does not plot figures centred at the origin point.

### ISSUE THREAD

**Issue by HongpingDeng** [pynbody/pynbody#268]
<img width="630" alt="screen shot 2015-08-07 at 19 38 20" src="https://cloud.githubusercontent.com/assets/13311743/9141844/f1dea9e4-3d3b-11e5-949a-a1df3ecff6fc.png">

**Comment by apontzen** [comment]
Can you post a link to the file? Otherwise we have no hope to reproduce this bug.

**Comment by HongpingDeng** [comment]
Hi,

This hdf5 file was produced by GIZMO( Philip Hopkins). I read it into pynbody using my own version of pynbody which I made some small adaptions in name mapping. You can read it directly using the standard pynbody because the gizmo hdf5 file is similar to gadget hdf5 file and gadgethdf.py can handle it. You can reproduce the bug when you plot the density of the gas family. Thanks a lot.

Regards,
Hongping

**Comment by apontzen** [comment]
No, we'll need your exact file to look at this for you. I have worked with many hdf5 files before and never seen this issue. It is unlikely to be format-related, and more likely to do with the specific configuration in your file.

**Comment by HongpingDeng** [comment]
Hi 

I am new to Github. Should I send you a pull request so you can view my files?

Thanks,
Hongping

**Comment by apontzen** [comment]
No, a pull request won't do this - the easiest thing is to put your file on a server of your own and paste a link.

**Comment by HongpingDeng** [comment]
Hi

Here are my files https://github.com/HongpingDeng/pynbody.git <https://github.com/HongpingDeng/pynbody.git>. It’s a little bit outdated because I pulled it from your repository about two weeks ago, but it works well in most cases. Testata locates at nose/testdata.

Regards,
Hongping

**Comment by apontzen** [comment]
Whoops! Turns out that the option to `center` in the sph plotting module was simply ignored. You can do the test first by 

pynbody.analysis.halo.center(s.gas,vel=False)

before you start. I have removed the inoperational 'center' option from the plot module. Thanks for the report.

BTW in debugging this I saw your gizmo classes - I would strongly advise against a copy and paste job like that because you will have to manually port your code if we ever fix bugs in our code (which we do regularly). If there are really differences that require a whole separate class to read, I'd recommend inheriting from GadgetHDFSnap/GadgetSnap instead. This page may help you: http://www.jesshamrick.com/2011/05/18/an-introduction-to-classes-and-inheritance-in-python/ ... But it seems like gadget and gizmo codes should be binary compatible anyway and I'm not clear why you need a whole new class to read gizmo.

**Comment by HongpingDeng** [comment]
Hi 

Thanks for solving the problem for me. 

The gizmo output are binary compatible to gadget output, but there are some new variables. I just build a name mapping rules for gizmo output and put gizmo class in higher priority in configuration file than gadget class, otherwise the code will use gadget name mapping rules. Should I just add new name mapping rules in the gadget name mapping rules, but there are some name conflicts. 

Regards,
Hongping

**Comment by apontzen** [comment]
Yes, I would advise you just do this by updating your configuration. You can always change it if you need to deal with another file, but the latest version will even allow you multiple keys inside `[gadgethdf-name-mapping]` and will pick the most appropriate one, e.g. you can have

```
[gadgethdf-name-mapping]
Masses: mass
Mass: mass
```

This facility is available under the branch hdf-naming-flexibility but should also be merged into master shortly.

**Comment by HongpingDeng** [comment]
Thanks, I will update my files.
