### ISSUE TITLE
Snapshot time doesn't exist in f.properties['time']  but does in f.header.time

### ISSUE THREAD

**Issue by DTHaydon** [pynbody/pynbody#284]
I have read in a GADGET file and noticed that within the properties there is no snapshot time information.
``` 
In [2]: f=pynbody.load('file/path')
In [3]: f.properties
Out[3]:
{'a': 1.0,
'boxsize': Unit("7.20e+04 kpc h**-1"),
'h': 0.72,
'omegaL0': 0.74,
'omegaM0': 0.26}
 ```
however this information is in the header
 ```
In [4]: f.header.time
Out[4]: 1.611599998176098

In [5]: type(f.header.time)
Out[5]: float
```
The value is without units, but should be in the units that result from having
velocity: km s\*\*-1 and distance: kpc 
ie. kpc km\*\*-1 s (= 977 Myr)

**Is there a reason why this time information is not being past to properties?**

As a quick fix to get this information into `f.properties['time']` I have been using:
 ```
f.properties['time'] = pynbody.array.SimArray(f.header.time, "kpc km**-1 s")
 ```
I also looked at using `f.infer_original_units("s")`:
```
f.properties['time'] = pynbody.array.SimArray(f.header.time, f.infer_original_units("s"))
```
as a slightly more 'organic' way to put the value into the units of the system; however, it cannot be converted into physical units:
```
In [11]: f.properties
Out[11]: 
{'a': 1.0,
 'boxsize': Unit("7.20e+04 kpc h**-1"),
 'h': 0.72,
 'omegaL0': 0.74,
 'omegaM0': 0.26,
 'time': SimArray(1.611599998176098, 's kpc a**-1/2 h**-1 km**-1')}

In [12]: f.physical_units()

In [13]: f.properties
Out[13]: 
{'a': 1.0,
 'boxsize': Unit("1.00e+05 kpc"),
 'h': 0.72,
 'omegaL0': 0.74,
 'omegaM0': 0.26,
 'time': SimArray(1.611599998176098, 's kpc a**-1/2 h**-1 km**-1')}*
```
which also doesn't seem quite right to me.

**Comment by apontzen** [comment]
Thanks for the bug report. Could you check branch issue-284 where I think I've fixed it?

- The problem with the time is a bug - for some reason it was ignoring the time entry in the header for cosmological snapshots.

- The problem with the units not converting correctly is that you are creating a SimArray rather than a raw Unit which is what it's looking for. Though arguably it should be happy to convert SimArrays in the properties too, I'm not attempting to fix this currently as it may have weird side-effects. In any case, the time entry should now be created and converted properly.

**Comment by DTHaydon** [comment]
I'm glad it was such a small fix.
Was the `if h.HubbleParam == 0.` line purely to test for the type of snapshot?

It's good to see the method of assigning units you use and I understand your reasoning for leaving SimArrays alone: they are an important part of pynbody and so modifications would need to be tested thoroughly!

But yes, this does seem to have solved the problem!
Thanks for looking into it.
