### ISSUE TITLE
Possible error in boxsize for ramses snaps?

### ISSUE THREAD

**Issue by earnric** [pynbody/pynbody#331]
So when I process a ramses snap with pynbody and access the _boxsize_ via:

`s.properties['boxsize'].in_units('kpc')`

I get one answer (that's different from the direct computation). For example - say I have loaded a snap at z = 9.5, 3 Mpc per h (0.71) comoving size. Pynbody tells me the scale at that redshift is:

```
s.properties['boxsize'].in_units('kpc')
401.68 kpc
```

However, when I compute the physical size via:

`3 Mpc/(1+9.5)/0.71 = 402.41 kpc

I believe these should be equal ... and this happens over all of my snaps. I've noticed that there's a const linear factor, ~0.998, that scales the value I get into the one returned by pynbody. Am I missing something or is this an error?

For a snap at z = 10

```
s.properties['boxsize'].in_units('kpc')
383.42
```
but
`3 Mpc/(1+10)/0.71 = 384.12 kpc

off by that same factor of .998... 

????

Rick S
ASU

**Comment by apontzen** [comment]
No idea I'm afraid. Perhaps you could dig a little deeper. What happens if you ask for it in units of Mpc a h^-1? Is the boxsize in the info.txt file consistent with what you expect, or with what pynbody returns? You can see explicitly how pynbody calculates the boxsize from the ramses info file at ramses.py:779 onwards.

**Comment by earnric** [comment]
Yea: the value in info*.txt agrees with what pynbody outputs... Now I have to figure out why ramses value for the boxsize in cm doesn't agree with the initial boxisize in Mpc * aexp / h ... (??)
