### ISSUE TITLE
halo properties in python 3

### ISSUE THREAD

**Issue by TobiBu** [pynbody/pynbody#347]
Hi,

after upgrading to python 3 and installing the latest pynbody version from github I get the following output when calling 
`h[1].properties.keys()` 
`dict_keys(['h', 'a', 'boxsize', 'omegaM0', 'halo_id', 'time', 'omegaL0'])`

especially `h[1].properties['children']` does not work anymore.

How do I resolve this issue?

**Comment by TobiBu** [comment]
I found out that when I go back to the version before the last commit, thus back to this commit: 

0c8443ba99a2b4194f0d20b29ca1bf154d3dbefa

this fixes the issue.

**Comment by apontzen** [comment]
Thanks, @mtremmel can you shed any light on this bug?

Just to confirm @tobibu are you saying this is not a python3 specific issue, just that you happened to upgrade simultaneously?

**Comment by TobiBu** [comment]
yes, it's not necessarily a python3 specific issue. I just updated to python3 and simultaneously updated pynbody.

**Comment by mtremmel** [comment]
Yes I found the issue. AHFCatalogue now uses "dummy halos" when reading in halo properties. When one calls for halo 1, say, using h[1], it reads in the simulation particles pertaining to halo 1, as well as the simulation properties, but fails to copy all of the properties originally read from the catalogue (they still exist, but in h._halos[1].properties instead, where h is the halo catalogue object). To ensure the functionality works the same as it did before, I have created a pull request that should fix this issue. In the meantime, the previous commit should work fine for you.

However, if all you need are the halo properties and not the particle information, I would use h._halos instead regardless, since this does not require reading in simulation data. It can make a big time difference, depending on the number of halos you are dealing with and the size of your simulation

**Comment by apontzen** [comment]
This issue should now be fixed in master; @TobiBu could you confirm?

**Comment by TobiBu** [comment]
Works perfectly fine. Thanks
