### ISSUE TITLE
Question about best way to use analysis.halo.virial_radius()

### ISSUE THREAD

**Issue by Morkney** [pynbody/pynbody#489]
I'm using the Pynbody function analysis.halo.virial_radius() to find the virial radius of a RAMSES halo, but I can only use it on one particular family (ie dark matter) at a time. If I attempt to use it over the whole particle group I return the error:

`KeyError: "'mass' is a family-level array for [<Family dm>, <Family star>]. To use it over the whole simulation you need either to delete it first, or create it separately for [<Family gas>]."`

I'm not sure how I follow the advice given in this error message, or if it's even appropriate to include stars/gas in the virial radius calculation. 

Any help would be greatly appreciated!

**Comment by Martin-Rey** [comment]
I believe the problem arises from this line:
https://github.com/pynbody/pynbody/blob/3fac16d1a2fe8170e73828613378021c4726a7ea/pynbody/analysis/halo.py#L158

The mass array is undefined at the snapshot level (because mass can be different for stars or dark matter particles), it is only defined at the family level, i.e snapshot.d or snapshot.stars.

The virial radius method might need some small tweaks to work robustly on DM+stars. Any thought s @apontzen ?

**Comment by Morkney** [comment]
Thank you @Martin-Rey and @apontzen,

Having `sim.gas['mass']` has indeed fixed the problem.
