### ISSUE TITLE
File nose/testdata is missing

### ISSUE THREAD

**Issue by texadactyl** [pynbody/pynbody#527]
There are 2 broken links to nose/testdata:

- docs/tutorials/example_code/testdata
- docs/testdata

**Comment by apontzen** [comment]
The documentation covers where to download the test data

**Comment by texadactyl** [comment]
In the documentation/installation (http://pynbody.github.io/pynbody/installation.html?highlight=testdata), the "downloads section" link takes one to a place (https://github.com/pynbody/pynbody/releases) where there is no testdata that I can find.  Did I miss something?

How about leaving a simple "testdata" file in ```nose``` so at least the links are not broken and those tests could run?  Good first start for the uninitiated.  Not your highest priority, I understand; you are as busy as I am.

**Comment by apontzen** [comment]
Thanks for pointing this out - the issue is that the most recent releases don't have an updated testdata tar. I'm adding this to the most recent release to prevent this confusion.

As for a simple test data, this isn't possible without a huge amount of work. As a reading library, pynbody needs 'realistic' files to test against, and working around this would require time which is better spent on other areas in need of improvement.
