### ISSUE TITLE
Circular dependency issue when trying to load `tform`

### ISSUE THREAD

**Issue by cphyc** [pynbody/pynbody#742]
**Describe the bug**

When trying to load `tform` for a RAMSES dataset, pynbody fails with a circular dependency error.

**To Reproduce**

```python
import pynbody
f = pynbody.load("testdata/ramses_new_format_cosmo_with_ahf_output_00110/")
f.star["tform"]  # crashes here
```
**Expected behaviour or result**
No error.

**Setup (please complete the following information):**
 - Pynbody version: 1.4.1
 
I tested with version all the way to 1b9d49f85f977bbacf1697e6c2858ab6c46d4be2 (in between 1.0.2 and 1.0.3) and it seems the bug has been here the entire time. I cannot check with earlier versions because one needs one of the commit in between 1.0.2 and 1.0.3 to load the dataset in the first place.

**Comment by apontzen** [comment]
I think the issue here is that there are not actually any star particles in this snapshot (nor the `testdata/ramses_rt_partial_output_00002` for which the tests are actually failing). The error message itself is perhaps unhelpful, but is caused by it not finding a `tform` array to load. Because there is a derived array that maps `aform` to `tform`, and another one that maps `tform` to `aform`, the final error is the circular dependency that one sees.
