### ISSUE TITLE
S.halos not working for the merger snapshot

### ISSUE THREAD

**Issue by Jhinfor4** [pynbody/pynbody#803]
Hello, I'm using pynbody to calculate the RC for a galaxy after the merger event in simulation (with GIZMO code).

It reports  "No halo catalogue found" when using s.halos().

whether pynodody is not applicable for the only two galaxies merger event snapshot? If not,  how should I use pynbody for this situation？

Hope you could help.

**Comment by apontzen** [comment]
If this is an isolated (non-cosmological) simulation, then almost certainly there will be no halos file associated with it. I am not really sure from your description what you are trying to achieve but if you have a specific question I am happy to try and help.

**Comment by Jhinfor4** [comment]
Yes, it's a non-cosmological simulation. I want to calculate the Rotation Curve for the galaxy after merger. So, I refer the tutorials of the "profile" part: loading the snapshot and find halo, but no halos in my simulation. 
Can I skip this step? just calculate the Rotation Curve with the particles in simulation without defining the halos.

**Comment by apontzen** [comment]
Yes, just call `pynbody.analysis.angmom.faceon` on the whole snapshot

Hope this helps!

**Comment by Jhinfor4** [comment]
Sorry, another problem happened
when I run :
s = pynbody.load()
h = pynbody.analysis.angmom.faceon(s)

it reports "Insufficient particles around center to get velocity"
but the simulation is high-resolution, contains 10825000 particles in total

**Comment by apontzen** [comment]
This likely means that the units have been incorrectly detected. Pynbody uses a sphere of 1kpc by default to find the velocity centre. 

You can change this option by passing the `cen_size` to [`pynbody.analysis.halo.center`](https://pynbody.readthedocs.io/latest/reference/_autosummary/pynbody.analysis.halo.center.html#pynbody.analysis.halo.center). 

In your case, my guess is that the unit system has been misinterpreted by pynbody so that what it thinks is 1kpc is actually very small (e.g. a confusion between Mpc and kpc). You may wish to call [`set_units_system`](https://pynbody.readthedocs.io/latest/reference/_autosummary/pynbody.snapshot.simsnap.SimSnap.html#pynbody.snapshot.simsnap.SimSnap.set_units_system)  right after loading the file, to put it right.

NB links here are to the much-improved documentation for v2 so if you are on v1 there may be a few small differences

**Comment by Jhinfor4** [comment]
Really appreciate, it works!
